# Generated by Django 5.0.1 on 2024-01-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_guest_can_puase_room_guest_can_pause_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='vote_to_skip',
            new_name='votes_to_skip',
        ),
    ]
